apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-app-categories
  namespace: {{ .Release.Namespace }}
data:
  mpcats.yaml: |
    application.security:
    - anchore-engine
    - aws-iam-authenticator
    - buildkite
    - cert-manager
    - dex
    - envoy
    - gce-ingress
    - gcloud-endpoints
    - jaeger-operator
    - kong
    - kube-hunter
    - kube-lego
    - magic-namespace
    - node-problem-detector
    - risk-advisor
    - sapho
    - sealed-secrets
    - sonarqube
    - vault-operator
    - voyager
    - xray
    cicd:
    - aerospike
    - artifactory
    - artifactory-ha
    - atlantis
    - concourse
    - docker-registry
    - drone
    - gitlab-ce
    - gitlab-ee
    - gocd
    - helm-exporter
    - jenkins
    - keel
    - rookout
    - spinnaker
    - swift
    - verdaccio
    - vsphere-cpi
    - weave-cloud
    - weave-scope
    - xray
    data.brokers:
    - centrifugo
    - memcached
    - rabbitmq-ha
    - rabbitmq
    data.storage:
    - apm-server
    - bookstack
    - chartmuseum
    - cloudserver
    - cockroachdb
    - consul
    - cosbench
    - couchbase-operator
    - couchdb
    - distribution
    - drupal
    - efs-provisioner
    - elasticsearch-curator
    - elasticsearch-exporter
    - elasticsearch
    - filebeat
    - gcloud-sqlproxy
    - hadoop
    - hazelcast
    - hlf-couchdb
    - ignite
    - influxdb
    - janusgraph
    - kubedb
    - mariadb
    - mediawiki
    - minio
    - mongodb-replicaset
    - mongodb
    - mssql-linux
    - mysql
    - mysqldump
    - neo4j
    - nextcloud
    - nfs-client-provisioner
    - nfs-server-provisioner
    - owncloud
    - parse
    - percona-xtradb-cluster
    - percona
    - pgadmin
    - phpmyadmin
    - postgresql
    - presto
    - prisma
    - prometheus
    - redis-ha
    - redis
    - rethinkdb
    - spark
    - stolon
    - verdaccio
    - zetcd
    development:
    - airflow
    - burrow
    - dask-distributed
    - dask
    - g2
    - hazelcast-jet
    - hl-composer
    - hlf-ca
    - hlf-ord
    - hlf-peer
    - horovod
    - kafka-manager
    - lamp
    - luigi
    - mailhog
    - mercure
    - node-red
    - osclass
    - pachyderm
    - phabricator
    - rookout
    - sapho
    - sealed-secrets
    - signalfx-agent
    - sonarqube
    - sonatype-nexus
    - spotify-docker-gc
    - spring-cloud-data-flow
    - tensorflow-serving
    - terracotta
    - verdaccio
    information.security:
    - ark
    - auditbeat
    - clamav
    - etcd-operator
    - gce-ingress
    - hoard
    - keycloak
    - kiam
    - kube2iam
    - nginx-lego
    - opa
    - openebs
    - openiban
    - openldap
    - openvpn
    - risk-advisor
    - velero
    monitoring:
    - chronograf
    - coscale
    - datadog
    - dmarc2logstash
    - elastalert
    - elasticsearch
    - eventrouter
    - fluent-bit
    - fluentd-elasticsearch
    - fluentd
    - goldpinger
    - grafana
    - graphite
    - graylog
    - hazelcast-jet
    - heapster
    - heartbeat
    - ingressmonitorcontroller
    - instana-agent
    - jasperreports
    - k8s-spot-rescheduler
    - k8s-spot-termination-handler
    - kapacitor
    - karma
    - katafygio
    - kibana
    - kube-slack
    - kube-state-metrics
    - kuberhealthy
    - kubernetes-dashboard
    - kubewatch
    - logdna-agent
    - logstash
    - metricbeat
    - metrics-server
    - msoms
    - newrelic-infrastructure
    - node-problem-detector
    - prometheus-adapter
    - prometheus-blackbox-exporter
    - prometheus-cloudwatch-exporter
    - prometheus-consul-exporter
    - prometheus-couchdb-exporter
    - prometheus-mongodb-exporter
    - prometheus-nats-exporter
    - prometheus-mysql-exporter
    - prometheus-node-exporter
    - prometheus-operator
    - prometheus-postgres-exporter
    - prometheus-pushgateway
    - prometheus-rabbitmq-exporter
    - prometheus-redis-exporter
    - prometheus-snmp-exporter
    - prometheus-to-sd
    - prometheus
    - reloader
    - searchlight
    - sematext-agent
    - sensu
    - seq
    - spartakus
    - stackdriver-exporter
    - stash
    - sumokube
    - sumologic-fluentd
    - sysdig
    - telegraf
    - traefik
    - uchiwa
    - wavefront
    - weave-scope
    networking:
    - ambassador
    - contour
    - coredns
    - express-gateway
    - external-dns
    - ipfs
    - linkerd
    - magic-ip-address
    - mcrouter
    - metallb
    - namerd
    - nats
    - oauth2-proxy
    - pomerium
    - signalsciences
    - socat-tunneller
    - stellar-core
    - unbound
    - unifi
    web:
    - bitcoind
    - cloudserver
    - distributed-tensorflow
    - dokuwiki
    - elastabot
    - elastic-stack
    - ethereum
    - factorio
    - ghost
    - hackmd
    - home-assistant
    - hubot
    - inbucket
    - jasperreports
    - joomla
    - kube-ops-view
    - magento
    - mattermost-team-edition
    - metabase
    - minecraft
    - moodle
    - nextcloud
    - nginx-ingress
    - nginx-ldapauth-proxy
    - odoo
    - opencart
    - orangehrm
    - osclass
    - owncloud
    - phabricator
    - phpbb
    - prestashop
    - prisma
    - redmine
    - rocketchat
    - schema-registry-ui
    - spark-history-server
    - suitecrm
    - superset
    - tensorflow-notebook
    - tomcat
    - voyager
    - wordpress
    - zeppelin
    devops:
    - aws-cluster-autoscaler
    - cerebro
    - chaoskube
    - cluster-autoscaler
    - cluster-overprovisioner
    - collabora-code
    - distributed-jmeter
    - fluent-bit
    - g2
    - gcp-night-king
    - goldpinger
    - inbucket
    - instana-agent
    - jaeger-operator
    - k8s-spot-rescheduler
    - kanister-operator
    - katafygio
    - kube-ops-view
    - locust
    - mission-control
    - phabricator
    - rookout
    - selenium
    - sentry
    - testlink
    - vsphere-cpi
